---

- name: Overwrite locale.gen
  ansible.builtin.copy:
    dest: "/etc/locale.gen"
    content: |
      en_US.UTF-8 UTF-8
      de_CH.UTF-8 UTF-8

- name: Select default locale
  ansible.builtin.debconf:
    name: locales
    question: locales/default_environment_locale
    value: en_US.UTF-8
    vtype: select

- name: Select supported locales
  ansible.builtin.debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: en_US.UTF-8 UTF-8, de_CH.UTF-8 UTF-8
    vtype: multiselect

- name: Generate locales
  ansible.builtin.shell: |
    export DEBIAN_FRONTEND=noninteractive
    locale-gen
    dpkg-reconfigure locales