- name: Create registry directory
  ansible.builtin.file:
    path: /home/podman/registry
    state: directory
    owner: podman
    group: podman
    mode: "0755"

- name: Configure local registry
  ansible.builtin.copy:
    dest: "/etc/containers/registries.conf.d/local-registry.conf"
    mode: "0644"
    content: |
      [[registry]]
      location = "{{ hostname }}:5443"
      insecure = true
  notify: Restart podman

- name: Flush handlers
  meta: flush_handlers

- name: Create registry pod
  become_user: podman
  become: true
  containers.podman.podman_container:
    name: image-registry
    image: registry
    state: present
    group_add: keep-groups
    userns: keep-id
    ports:
      - "5000:5000"
    volume:
      - /home/podman/registry:/var/lib/registry
    generate_systemd:
      path: "/home/podman/.config/systemd/user"
      restart_policy: always
      names: true

- name: Enable and start registry container service
  become_user: "podman"
  become: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/1001"
  ansible.builtin.systemd:
    name: "container-image-registry"
    scope: "user"
    state: started
    daemon_reload: "{{ systemd_daemon_reload }}"
    enabled: true
