
- name: Redirect external http and https traffic to non-privileged ports
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    marker: "# {mark} ANSIBLE MANAGED NAT CHAIN"
    insertbefore: '^\*filter'
    block: |
      *nat
      :PREROUTING ACCEPT [0:0]
      -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
      -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8443
      -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
      -A PREROUTING -p tcp --dport 8443 -j REDIRECT --to-port 443
      -A OUTPUT -s 127.0.0.1 -p tcp --dport 80 -j REDIRECT --to-port 8080
      -A OUTPUT -s 127.0.0.1 -p tcp --dport 443 -j REDIRECT --to-port 8443
      COMMIT
  notify: Reload ufw rules

- name: Allow redirected http
  community.general.ufw:
    rule: allow
    proto: tcp
    port: '8080'

- name: Allow redirected https
  community.general.ufw:
    rule: allow
    proto: tcp
    port: '8443'

- name: Create Webserver Pod
  become_user: podman
  become: true
  containers.podman.podman_pod:
    name: webserver
    state: created
    userns: keep-id
    ports:
      - "8080:8080"
      - "8443:8443"
    generate_systemd:
      path: "/home/podman/.config/systemd/user"
      restart_policy: always
      names: true

- name: Enable and start Webserver Pod service
  become_user: "podman"
  become: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/1001"
  ansible.builtin.systemd:
    name: "pod-webserver"
    scope: "user"
    state: started
    daemon_reload: true
    enabled: true
