
- name: Install dependencies for ansible openssl_certificate and htpasswd
  ansible.builtin.apt:
    pkg:
      - python3-passlib
      - python3-openssl
      - acl

- name: Create proxy data directory
  ansible.builtin.file:
    path: "{{ container_data_dir }}/proxy"
    state: directory
    owner: "podman"
    group: "podman"
    mode: "0755"

- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ container_data_dir }}/proxy/cert.key"
    owner: "podman"
    group: "podman"
    mode: "0640"

- name: Generate an OpenSSL Certificate Signing Request with subjectAltName extension
  community.crypto.openssl_csr:
    path: '{{ container_data_dir }}/proxy/cert.csr'
    privatekey_path: "{{ container_data_dir }}/proxy/cert.key"
    common_name: '{{ hostname }}'
    subject_alt_name: 'DNS:{{ hostname }}'

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ container_data_dir }}/proxy/cert.pem"
    privatekey_path: "{{ container_data_dir }}/proxy/cert.key"
    csr_path: "{{ container_data_dir }}/proxy/cert.csr"
    provider: selfsigned
    owner: "podman"
    group: "podman"

- name: Create registry htpasswd file
  community.general.htpasswd:
    path: "{{ container_data_dir }}/proxy/registry.htpasswd"
    name: registry
    password: "{{ lookup('community.general.passwordstore', hostname + '/registry', create=true) }}"
    crypt_scheme: bcrypt
    owner: "podman"
    group: "podman"
    mode: "0640"

- name: Write nginx proxy conf
  ansible.builtin.template:
    src: templates/nginx-proxy.conf.j2
    dest: "{{ container_data_dir }}/proxy/nginx.conf"
    mode: "0644"
    owner: "podman"
    group: "podman"

- name: Create nginx proxy container
  become_user: "podman"
  become: true
  containers.podman.podman_container:
    name: nginx-proxy
    image: nginxinc/nginx-unprivileged:alpine
    group_add: keep-groups
    pod: webserver
    recreate: true
    state: started
    restart_policy: always
    volume:
      - "{{ container_data_dir }}/proxy/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro"
      - "{{ container_data_dir }}/proxy:/tmp/nginx"
