- name: Reload ufw rules
  become: true
  systemd:
    name: "ufw"
    state: reload
    enabled: true

- name: Restart podman
  become: true
  systemd:
    name: "podman"
    state: restarted
    enabled: true