- name: Install apt_proxy Service
  ansible.builtin.import_tasks: apt-cacher-ng.yml
  when: "'service_apt_proxy' in group_names"

- name: Configure clients to use apt_proxy
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/4132-apt-proxy.conf
    regexp: "^Acquire::http::Proxy "
    line: "Acquire::http::Proxy \"http://{{ groups['service_apt_proxy'][0] }}:3142\";"
    mode: "0644"
    create: yes
  when: "'service_apt_proxy' not in group_names"
