- name: Generate locales
  ansible.builtin.command: locale-gen

- name: Restart keyboard service
  ansible.builtin.systemd:
    name: "keyboard-setup"
    state: restarted

- name: Restart Avahi-Daemon
  ansible.builtin.systemd:
    name: "avahi-daemon"
    state: restarted

- name: Start ufw
  community.general.ufw:
    state: enabled

- name: Reload ufw
  community.general.ufw:
    state: reloaded