- name: Create hello world pod
  become_user: podman
  become: true
  containers.podman.podman_container:
    debug: true
    name: hello-world
    image: nginx:alpine-slim
    state: present
    group_add: keep-groups
    userns: keep-id
    volume:
      - /data:/data
    generate_systemd:
      path: "/home/podman/.config/systemd/user"
      restart_policy: always
      names: true

- name: enable and start container service
  become_user: "podman"
  become: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/1001"
  systemd:
    name: "container-hello-world"
    scope: "user"
    daemon_reload: "{{ systemd_daemon_reload }}"
    state: started
    enabled: true
