---

- name: Install podman (rootless)
  ansible.builtin.apt:
    pkg:
    - fuse-overlayfs
    - slirp4netns
    - uidmap
    - podman

- name: Configure containter registrie
  ansible.builtin.copy:
    dest: "/etc/containers/registries.conf.d/registries.conf"
    content: |
      unqualified-search-registries = ['docker.io']

- name: Set storage to fuse-overlayfs
  ansible.builtin.copy:
    dest: "/etc/containers/storage.conf"
    content: |
      [storage]
        driver = "overlay"
      [storage.options.overlay]
        mount_program = "/usr/bin/fuse-overlayfs"

- name: Create podman user
  ansible.builtin.user:
    name: podman
    groups: data
    shell: /usr/sbin/nologin

- name: Set users to create sub{u|g}ids for
  set_fact:
    subid_users:
      - podman

- name: Generate subuids & subgids
  include_role:
    name: subuid_subgid

- name: Add data group as subgid
  ansible.builtin.lineinfile:
    path: /etc/subgid
    state: present
    regexp: '^podman:99:1'
    line: 'podman:99:1'