---

- name: Install git
  ansible.builtin.apt:
    pkg:
    - git

- name: Clone conetent and config
  git:
    repo: https://github.com/c0linh/nginx-proxy.git
    dest: /home/podman/container/nginx-proxy
    clone: yes
    update: yes

- name: Start nginx proxy
  containers.podman.podman_container:
    name: nginx-proxy
    image: nginx:alpine-slim
    state: present
    recreate: true
    volume:
      - /home/podman/container/nginx-proxy/static:/usr/share/nginx/html
      - /home/podman/container/nginx-proxy/proxy.conf:/etc/nginx/conf.d/default.conf
      - /home/podman/container/nginx-proxy/.htaccess:/usr/share/nginx/.htaccess 
    ports:
      - "8080:80"
    generate_systemd:
      restart_policy: always
      names: true
      container_prefix: proxy