- name: Set default locale to english
  ansible.builtin.copy:
    dest: "/etc/default/locale"
    mode: "0644"
    content: |
      LANG=en_US.UTF-8
      LANGUAGE=en_US:en
      LC_TIME=de_CH.UTF-8
      LC_MEASUREMENT=de_CH.UTF-8
      LC_MESSAGES=en_US.UTF-8
      LC_MONETARY=de_CH.UTF-8
      LC_NUMERIC=de_CH.UTF-8
      LC_PAPER=de_CH.UTF-8

- name: Set English and swiss-german in locale.gen
  ansible.builtin.lineinfile:
    mode: "0644"
    create: True
    path: "/etc/locale.gen"
    regexp: "^#?{{ item }}"
    line: "{{ item }}"
  loop:
    - "en_US.UTF-8 UTF-8"
    - "de_CH.UTF-8 UTF-8"

- name: Install console and keyboard packaged
  block:
    - name: Install keyboard related packages
      ansible.builtin.apt:
        cache_valid_time: "43200"
        pkg:
          - keyboard-configuration
          - console-setup
  rescue:
    - name: Wait for apt lock - call sleep - blunt rescue attempt
      ansible.builtin.command: |
        sleep 2
    - name: Install keyboard related packages - with a hammer
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - keyboard-configuration
          - console-setup

- name: Set keyboard layout to swiss-german
  ansible.builtin.copy:
    dest: "/etc/default/keyboard"
    mode: "0644"
    content: |
      XKBMODEL="pc105"
      XKBLAYOUT="ch"
      XKBVARIANT="nodeadkeys"
      XKBOPTIONS="ctrl:nocaps,terminate:ctrl_alt_bksp"
      BACKSPACE="guess"
  notify: Restart keyboard service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers