- name: Ensure read rights on ansible folger
  ansible.builtin.file:
    path:  /etc/ansible
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create facts.d directory
  ansible.builtin.file:
    path:  /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Apt config
  ansible.builtin.import_tasks: apt-config.yml
- name: Locale and Keyboard
  ansible.builtin.import_tasks: locale-keyboard.yml
- name: Apt Update
  ansible.builtin.import_tasks: apt-upgrade.yml
- name: UFW Setup
  ansible.builtin.import_tasks: ufw.yml
- name: Avahi-Daemon Setup
  ansible.builtin.import_tasks: avahi-daemon.yml

- name: Flush handlers (base)
  ansible.builtin.meta: flush_handlers