- name: Install ufw
  ansible.builtin.apt:
    cache_valid_time: "43200"
    pkg:
      - ufw
  notify:
    - Start ufw

- name: Set default outgoing policies
  community.general.ufw:
    direction: outgoing
    policy: allow
  notify:
    - Reload ufw

- name: Set default incomming policies
  community.general.ufw:
    direction: incoming
    policy: deny
  notify:
    - Reload ufw

#TODO May restrict?
- name: Allow SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
  notify: Reload ufw