- name: Mediacenter Hosts
  hosts:
    - mediacenter.local
  # roles:
  #   - base
  #   - role: hifis.unattended_upgrades
  #     unattended_origins_patterns:
  #       - 'origin=Debian,codename=${distro_codename},label=Debian-Security' # security updates
  #       - 'o=Debian,codename=${distro_codename},label=Debian' # updates including non-security updates
  #       - 'o=Debian,codename=${distro_codename},a=proposed-updates'
  #   - podman
  #   # - mediaserver

  tasks:
    - name: Setup
      ansible.builtin.include_role:
        name: base
        apply:
          tags:
            - setup
      tags: setup
    - name: Unattended updates
      ansible.builtin.include_role:
        name: hifis.unattended_upgrades
        apply:
          tags:
            - setup
      tags:
        - setup
    - name: Podman
      ansible.builtin.include_role:
        name: podman
        apply:
          tags:
            - podman
      tags:
        - podman
  vars_files:
    - "env_vars/{{ env }}.yml"
  become: true
