- name: Mediacenter Hosts
  hosts:
    - dev
  roles:
    - base
    - role: hifis.unattended_upgrades
      unattended_origins_patterns:
        - 'origin=Debian,codename=${distro_codename},label=Debian-Security' # security updates
        - 'o=Debian,codename=${distro_codename},label=Debian' # updates including non-security updates
        - 'o=Debian,codename=${distro_codename},a=proposed-updates'
    - podman
    # - mediaserver
  vars_files:
    - "env_vars/{{ env }}.yml"
  become: true
