- name: All machines of home.c0lin.ch
  hosts: all
  roles:
    - base
    - role: hifis.unattended_upgrades
      unattended_origins_patterns:
        - 'origin=Debian,codename=${distro_codename},label=Debian-Security' # security updates
        - 'o=Debian,codename=${distro_codename},label=Debian' # updates including non-security updates
        - 'o=Debian,codename=${distro_codename},a=proposed-updates'
  become: true

- name: DMZ of home.c0lin.ch
  hosts: server_vm
  roles:
    - podman
  become: true

- name: Mediacenter
  hosts: mediacenter
  roles:
    - mediacenter
  become: true
